[package]
name = "aws-billing-notification"
version = "0.1.0"
authors = ["xKerman <xKhorasan@gmail.com>"]
edition = "2018"
autobins = false

[dependencies]
lambda = { package = "lambda_runtime", version = "0.1" }
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
log = "^0.4"
simple_logger = "^1"
rusoto_core = "0.35.0"
rusoto_cloudwatch = "0.35.0"
rusoto_ssm = "0.35.0"
chrono = "0.4"
slack-hook = "0.7"
openssl-probe = "0.1.2"

[[bin]]
name = "bootstrap"
path = "src/main.rs"
