AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  SlackWebhookUrl:
    Type: String
    Description: Incoming Webhook URL
Resources:
  AwsBillingNotificationLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-billing-notification
      Runtime: provided
      Handler: bootstrap
      CodeUri: target/rust.zip
      Role: !GetAtt AwsBillingNotificationIamRole.Arn
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          RUST_BACKTRACE: 1
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
  AwsBillingNotificationIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
